
import javax.swing.table.DefaultTableModel;

public class TestFrame extends javax.swing.JFrame {

    Data data;

    public TestFrame() {
        initComponents();
        this.setSize(960, 460);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tResults = new javax.swing.JTable();
        bDataLoad = new javax.swing.JButton();
        bMake = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfGroupSize = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test Librería TEAM-B v1.0");
        getContentPane().setLayout(null);

        tData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 53, 452, 303);

        tResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tResults);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(482, 53, 452, 303);

        bDataLoad.setText("Cargar datos");
        bDataLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataLoadActionPerformed(evt);
            }
        });
        getContentPane().add(bDataLoad);
        bDataLoad.setBounds(12, 374, 452, 25);

        bMake.setText("Conformar");
        bMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMakeActionPerformed(evt);
            }
        });
        getContentPane().add(bMake);
        bMake.setBounds(482, 374, 452, 25);

        jLabel1.setText("Tamaño de los grupos:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 13, 133, 16);
        getContentPane().add(tfGroupSize);
        tfGroupSize.setBounds(150, 13, 50, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDataLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataLoadActionPerformed
        // TODO add your handling code here:
        data = new Data("G2.txt", Integer.parseInt(tfGroupSize.getText()));
        Object[][] dataO = new Object[data.getCurrentData().length][data.getCurrentData()[0].split(",").length];
        String[] columnNames = new String[data.getCurrentData()[0].split(",").length];
        String[] tmp;

        columnNames[0] = "ID";
        columnNames[1] = "NOMBRE";
        for (int i = 2; i < columnNames.length; i++) {
            columnNames[i] = "C" + (i - 1);
        }
        for (int i = 0; i < data.getCurrentData().length; i++) {
            tmp = data.getCurrentData()[i].split(",");
            for (int j = 0; j < tmp.length; j++) {
                dataO[i][j] = tmp[j];
            }
        }
        tData.setModel(new DefaultTableModel(dataO, columnNames));
    }//GEN-LAST:event_bDataLoadActionPerformed

    private void bMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMakeActionPerformed
        // TODO add your handling code here:
        int generations = 0;
        long starTime = System.currentTimeMillis();

        GA ga = new GA(data, 2500, 40, 0.01f);
        ga.initialPopulation();
        ga.checkFitnessMinimize();
        ga.evaluation();
        while (generations < 100) {
            ga.rouletteWheelW((int) Math.ceil(ga.getPopulationSize() * ((double) ga.getSelectionPercent() / 100)));
            ga.reproduction();
            ga.mutation();
            ga.checkFitnessMinimize();
            ga.evaluation();
            generations++;
        }
        long endTime = System.currentTimeMillis() - starTime;
        System.out.println("Mejor fitness: " + ga.getPopulation()[ga.getBestPosition()].getRawFitness());
        System.out.println("Tiempo: " + endTime);

        int[][] results = ga.getPopulation()[ga.getBestPosition()].getGenes();
        Object[][] dataO = new Object[results.length * results[0].length][2];
        String[] columnNames = new String[2];
        int idx = 0;

        columnNames[0] = "GRUPO";
        columnNames[1] = "ID";
        for (int i = 0; i < results.length; i++) {
            for (int j = 0; j < results[i].length; j++) {
                dataO[idx][0] = i + 1;
                dataO[idx][1] = results[i][j];
                idx++;
            }
        }
        tResults.setModel(new DefaultTableModel(dataO, columnNames));
    }//GEN-LAST:event_bMakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDataLoad;
    private javax.swing.JButton bMake;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tData;
    private javax.swing.JTable tResults;
    private javax.swing.JTextField tfGroupSize;
    // End of variables declaration//GEN-END:variables
}
